fix(arguments): ignore -psn_0 argument on macOS
On macOS a file with the quarantine flag will cause an error on game start:

```
error: unrecognized arguments: -psn_0_some_number_here
```

Unfortunately the end user has no control over how the renpy engine is packaged
and/or embedded. Thus let's ignore this argument.